### ISSUE TITLE
It seems like CANMessage::id is not 32bit

### ISSUE THREAD

**Issue by roman-kudinov** [pierremolinaro/acan2515Tiny#2]
It looks like the effective bit depth of CANMessage::id is not 32-bit. The following pseudo-code fails:

send()
{
CANMessage message;
message.id = deviceID << 16; //deviceID is in the range [1;0xff]
message.id |= command;        //command < 0xffff
trytosend();
}

receive()
{
CANMessage message;
can.receive(message);

println(message.id);        //prints 'command', e.g. the high word value is lost
}

If I shift deviceID for 8 bits, e.g. 'message.id = deviceID << 8;' and make sure command is in the range [0;0xff] everthing works fine.

**Comment by pierremolinaro** [comment]
Hello,

What is your micro-controller ? It you use a 8-bit micro-controller (Arduino Uno, ArduinoMega, …), the int type is 16-bit wide. integer literal values have by default int type.

For ensuring a 32-bit unsigned integer value, you should use the "UL" posfix. Try:
message.id = 1UL << 16;

Regards,

Pierre Molinaro

**Comment by roman-kudinov** [comment]
I use Arduino Uno ATMega328P.

I used uint32_t cast because Arduino IDE printed the appropriated warning. I even tried to assign 65536 explicitly to message id. println(message.id) in the function send() printed '65536', but println(message.id) in the function receive() printed '0'.

**Comment by roman-kudinov** [comment]
I can make the simple sketch that reproduces the problem if it helps.

**Comment by roman-kudinov** [comment]
P.S. I didn't test how it works in LoopBackMode. I tested in NormalMode with the physical connection.

**Comment by pierremolinaro** [comment]
You send standard frames. Standard frames identifiers are 11-bit. 

If you want a 17-bit identifier, use extended frames (29-bits identifiers).
send()
{
CANMessage message;
message. <http://message.id/>ext = true;
message.id <http://message.id/> = 1UL << 16;
message.id <http://message.id/> |= command;
trytosend();
}
